export const carMakes = [
  "Toyota",
  "Honda",
  "Ford",
  "Chevrolet",
  "Nissan",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Volkswagen",
  "Hyundai",
  "Kia",
  "Subaru",
  "Mazda",
  "Lexus",
  "Jeep",
  "Ram",
  "GMC",
  "Cadillac",
  "Volvo",
  "Buick",
  "Acura",
  "Infiniti",
  "Chrysler",
  "Land Rover",
  "Lincoln",
  "Porsche",
  "Mitsubishi",
  "Jaguar",
  "Tesla",
  "Fiat",
  "Mini",
  "Audi",
  "Genesis",
  "Bentley",
  "Ferrari",
  "Maserati",
  "McLaren",
  "Alfa Romeo",
  "Rolls-Royce",
  "Bugatti",
  "Lamborghini",
  "Lotus",
  "Koenigsegg",
  "Pagani",
];

export const carModels = {
  Toyota: [
    "Camry",
    "Corolla",
    "Rav4",
    "Tacoma",
    "Highlander",
    "4Runner",
    "Sienna",
    "Avalon",
    "Prius",
  ],
  Honda: [
    "Civic",
    "Accord",
    "CR-V",
    "Pilot",
    "Odyssey",
    "HR-V",
    "Fit",
    "Ridgeline",
    "Insight",
  ],
  Ford: [
    "F-150",
    "Escape",
    "Explorer",
    "Focus",
    "Fusion",
    "Mustang",
    "Edge",
    "Ranger",
    "Expedition",
  ],
  Chevrolet: [
    "Silverado",
    "Equinox",
    "Malibu",
    "Traverse",
    "Tahoe",
    "Camaro",
    "Suburban",
    "Colorado",
    "Impala",
  ],
  Nissan: [
    "Altima",
    "Rogue",
    "Sentra",
    "Murano",
    "Pathfinder",
    "Maxima",
    "Frontier",
    "Titan",
    "Versa",
  ],
  BMW: [
    "3 Series",
    "5 Series",
    "X5",
    "X3",
    "7 Series",
    "X1",
    "4 Series",
    "X7",
    "X6",
  ],
  "Mercedes-Benz": [
    "C-Class",
    "E-Class",
    "GLC",
    "GLE",
    "A-Class",
    "S-Class",
    "GLA",
    "CLA",
    "G-Class",
  ],
  Audi: ["A4", "Q5", "A3", "Q7", "A6", "Q3", "A5", "Q8", "A8"],
  Volkswagen: [
    "Jetta",
    "Tiguan",
    "Passat",
    "Atlas",
    "Golf",
    "Arteon",
    "Taos",
    "ID.4",
    "Atlas Cross Sport",
  ],
  Hyundai: [
    "Elantra",
    "Tucson",
    "Sonata",
    "Santa Fe",
    "Kona",
    "Palisade",
    "Veloster",
    "Venue",
    "Accent",
  ],
  Kia: [
    "Sorento",
    "Sportage",
    "Soul",
    "Telluride",
    "Forte",
    "Rio",
    "Stinger",
    "Cadenza",
    "K5",
  ],
  Subaru: [
    "Outback",
    "Forester",
    "Legacy",
    "Crosstrek",
    "Impreza",
    "Ascent",
    "WRX",
  ],
  Mazda: ["CX-5", "Mazda3", "CX-9", "CX-30", "Mazda6", "MX-5 Miata", "CX-3"],
  Lexus: ["RX", "NX", "ES", "UX", "RX L", "IS", "GX", "RC", "LS"],
  Jeep: [
    "Grand Cherokee",
    "Wrangler",
    "Cherokee",
    "Renegade",
    "Compass",
    "Gladiator",
  ],
  Ram: ["1500", "2500", "3500", "ProMaster", "ProMaster City"],
  GMC: ["Sierra", "Terrain", "Acadia", "Yukon", "Canyon"],
  Cadillac: ["XT5", "XT4", "Escalade", "XT6", "CT4", "CT5"],
  Volvo: ["XC90", "XC60", "XC40", "S60", "V60", "S90"],
  Buick: ["Encore", "Enclave", "Envision", "Regal", "LaCrosse"],
  Acura: ["MDX", "RDX", "TLX", "ILX", "RLX"],
  Infiniti: ["QX60", "Q50", "QX50", "QX80", "Q60", "QX30"],
  Chrysler: ["Pacifica", "300"],
  "Land Rover": [
    "Range Rover",
    "Discovery",
    "Range Rover Sport",
    "Defender",
    "Range Rover Velar",
    "Discovery Sport",
  ],
  Lincoln: ["Navigator", "Aviator", "Corsair", "Nautilus", "Continental"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718"],
  Mitsubishi: [
    "Outlander",
    "Outlander Sport",
    "Eclipse Cross",
    "Mirage",
    "Mirage G4",
  ],
  Jaguar: ["F-PACE", "XE", "F-TYPE", "XF", "I-PACE"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck", "Roadster"],
  Fiat: ["500", "500X", "500L"],
  Mini: ["Cooper", "Countryman", "Clubman", "Convertible", "Hardtop"],
  Genesis: ["G80", "G70", "GV80", "G90"],
  Bentley: ["Bentayga", "Continental", "Flying Spur"],
  Ferrari: ["488", "812 Superfast", "F8 Tributo", "Roma", "Portofino"],
  Maserati: ["Levante", "Ghibli", "Quattroporte"],
  McLaren: ["570S", "720S", "GT"],
  "Alfa Romeo": ["Giulia", "Stelvio"],
  "Rolls-Royce": ["Phantom", "Cullinan", "Ghost", "Wraith"],
  Bugatti: ["Chiron", "Divo"],
  Lamborghini: ["Urus", "Huracan", "Aventador"],
  Lotus: ["Evora", "Elise", "Exige"],
  Koenigsegg: ["Jesko", "Regera", "Gemera"],
  Pagani: ["Huayra", "Zonda"],
};
