import "./globals.css";
import Providers from "../components/providers";

import Footer from "../components/Footer";
import NavBar from "../components/NavBar";

export const metadata = {
  title: "Car Rental",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {" "}
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
